/**
 * Global icons
 */

import '@fortawesome/fontawesome-pro/svgs/regular/circle-notch.svg'
import '@surf/icons/global/address-card.svg'
import '@surf/icons/global/anchor.svg'
import '@surf/icons/global/app-android.svg'
import '@surf/icons/global/app-ios.svg'
import '@surf/icons/global/arrow-down.svg'
import '@surf/icons/global/arrow-left.svg'
import '@surf/icons/global/arrow-right.svg'
import '@surf/icons/global/bullseye.svg'
import '@surf/icons/global/cake-candles.svg'
import '@surf/icons/global/calendar-checked.svg'
import '@surf/icons/global/calendar-days.svg'
import '@surf/icons/global/calendar.svg'
import '@surf/icons/global/caret-down.svg'
import '@surf/icons/global/caret-up.svg'
import '@surf/icons/global/chevron-down.svg'
import '@surf/icons/global/chevron-left-regular.svg'
import '@surf/icons/global/chevron-up.svg'
import '@surf/icons/global/clipboard 2.svg'
import '@surf/icons/global/clock.svg'
import '@surf/icons/global/code.svg'
import '@surf/icons/global/coins.svg'
import '@surf/icons/global/comment.svg'
import '@surf/icons/global/comments.svg'
import '@surf/icons/global/document.svg'
import '@surf/icons/global/email.svg'
import '@surf/icons/global/envelope.svg'
import '@surf/icons/global/euro.svg'
import '@surf/icons/global/eye.svg'
import '@surf/icons/global/file-pdf.svg'
import '@surf/icons/global/file.svg'
import '@surf/icons/global/folder.svg'
import '@surf/icons/global/folders.svg'
import '@surf/icons/global/globe.svg'
import '@surf/icons/global/hamburger.svg'
import '@surf/icons/global/heart.svg'
import '@surf/icons/global/info-circle.svg'
import '@surf/icons/global/layer-group.svg'
import '@surf/icons/global/lightbulb.svg'
import '@surf/icons/global/list-ol.svg'
import '@surf/icons/global/list-tree.svg'
import '@surf/icons/global/long-arrow-left.svg'
import '@surf/icons/global/long-arrow-right.svg'
import '@surf/icons/global/marker.svg'
import '@surf/icons/global/message.svg'
import '@surf/icons/global/messages.svg'
import '@surf/icons/global/network-wired.svg'
import '@surf/icons/global/newspaper.svg'
import '@surf/icons/global/notebook.svg'
import '@surf/icons/global/paper-plane.svg'
import '@surf/icons/global/pencil.svg'
import '@surf/icons/global/print.svg'
import '@surf/icons/global/search.svg'
import '@surf/icons/global/social-facebook.svg'
import '@surf/icons/global/social-instagram.svg'
import '@surf/icons/global/social-linkedin.svg'
import '@surf/icons/global/social-mastodon.svg'
import '@surf/icons/global/social-tiktok.svg'
import '@surf/icons/global/social-twitter.svg'
import '@surf/icons/global/social-vimeo.svg'
import '@surf/icons/global/social-youtube.svg'
import '@surf/icons/global/star.svg'
import '@surf/icons/global/surf-approved.svg'
import '@surf/icons/global/surf-developed.svg'
import '@surf/icons/global/tag.svg'
import '@surf/icons/global/tree.svg'
import '@surf/icons/global/turntable.svg'
import '@surf/icons/global/vials.svg'
import '@surf/icons/global/wifi.svg'

/**
 * SURF
 */

import '@surf/icons/surf/surf-logo.svg'
